# @Author: Your name
# @Date:   2021-09-19 19:11:51
# @Last Modified by:   Your name
# @Last Modified time: 2021-09-19 22:14:57
###
# Install git and clone the repo

- name: Set up configuration
  apt:
    pkg: 
      - git
      - pip3
    state: latest
  become: yes

- name: Clone or pull the latest code
  git:
    repo: https://github.com/navodissa/cse_price_api.git
    dest: /home/ubuntu/cse_price