# @Author: Your name
# @Date:   2021-09-19 19:11:51
# @Last Modified by:   Your name
# @Last Modified time: 2021-09-19 19:22:12
###
# Install git and clone the repo

- name: Set up configuration
  yum:
    name: git
    state: latest
  become: yes

- name: Clone or pull the latest code
  git:
    repo: {{ code_repository_url }}
    dest: {{ app_dir }}