# @Author: Your name
# @Date:   2021-09-19 19:23:38
# @Last Modified by:   Your name
# @Last Modified time: 2021-09-19 19:25:01
# Setup project required dependencies

- name: Install Dependencies
  pip:  requirements= {{ app_dir }}/requirements.txt
  become: yes