# @Author: Your name
# @Date:   2021-09-21 20:37:29
# @Last Modified by:   Your name
# @Last Modified time: 2021-09-21 22:00:24
# Install Docker and configure it

# - name: Update Repos
#   command: apt-get update
#   become: yes

# - name: Set up pip
#   apt:
#     pkg:
#       - python3-pip
#       - yum
#     state: latest
#   become: yes

# - name: Docker Repo
#   yum_repository:
#     name: docker
#     description: Docker yum repo
#     baseurl: https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64
#     gpgcheck: no

# - name: Docker Installation
#   package:
#     name: docker-ce
#     state: present

# - name: Install through Docker
#   command: pip3 install docker-py
#   ignore_errors: true

- name: apt update
  apt:
    update_cache: yes
  become: yes

- name: Install prerequisites for Docker repository
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
  become: yes

- name: add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker apt repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  become: yes

- name: install docker and it's dependencies
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: yes

- name: start and enable docker daemon
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Django Image
  docker_image:
    name: "navoda/django-api"
    source: pull

- name: Launch django-api container
  docker_container:
    name: apiserver
    exposed_ports:
      - "8000"
    ports:
      - "8000:8000"
